#ifndef __OLLIOS_EVENTDEF_H
#define __OLLIOS_EVENTDEF_H

#include "types.h"

#define EVENT_TARGET_ANY 0x00000000
#define EVENT_TARGET_MAIN 0x00000001
#define EVENT_TARGET_ALL 0xFFFFFFFF

#define EVENT_TYPE_STARTUP 1

#endif
