#ifndef __OLLIOS_EVENTDEF_H
#define __OLLIOS_EVENTDEF_H

#include "types.h"

#define EVENT_TARGET_ANY 0x00000000
#define EVENT_TARGET_MAIN 0x00000001
#define EVENT_TARGET_ALL 0xFFFFFFFF

#define EVENT_TYPE_STARTUP  0x1
#define EVENT_TYPE_KEYBOARD 0x2

#define EVENT_TYPE_DEVICE_PUBLISH  0x3
#define EVENT_TYPE_DEVICE_DISCOVER 0x4
#define EVENT_TYPE_DEVICE_WRITE    0x5
#define EVENT_TYPE_DEVICE_READ     0x6
#define EVENT_TYPE_DEVICE_SEEK     0x7


#endif
